name: vision 
channels:
  - pytorch
  - nvidia 
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pytorch==2.0.1 
  - torchvision==0.15.2 
  - torchaudio==2.0.2  
  - pytorch-cuda=11.7 
  - ipython 
  - faiss
  - numpy
  - pandas
  - rerun
  - scikit_learn
  - tqdm
  - xformers
  - pip: